### ISSUE TITLE
Add new JPL ephemeris data to ASCOT

### ISSUE THREAD

**Issue by varenius** [varenius/ascot#49]
https://iopscience.iop.org/article/10.3847/1538-3881/abd414

**Comment by TobNilsson** [comment]
I have included the DE440 ephemeris in the latest update (apriori_files/linux_p1550p2650.440). To use them, modify the config files accordingly. However, I am not sure if we should include the ephemeris in ASCOT, or tell the user to download them from jpl (https://ssd.jpl.nasa.gov/ftp/eph/planets/Linux/). In fact, ASCOT should be able to use all of the currently available JPL ephemeris as well as future ones, as long as the file format is unchanged.
