### ISSUE TITLE
Check if ASCOT reports ERP as PWL

### ISSUE THREAD

**Issue by varenius** [varenius/ascot#55]
According to email to all analysis people from John G 2014-06-14, reminded by Alex N 2021-07-01, it would be good if software estimated and reported the Earth Rotation Parameters (ERPs) with both offsets and rates. As Alex writes:

> In the VGOS era, but also with bigger legacy networks, the VLBI observations are sensitive enough that ERP should not only be estimated with offsets and rates but routinely with higher time resolution. This is best achieved by parameterization with piece-wise linear offsets because this is the only way to also combine the results of different analysis centers. Estimation of PWL offsets brings with it the chance that the IVS ACs report their a prioris consistently and thus improve the combination, a fact which is not guaranteed with the UT1 rate/LOD because of the incomplete information in the SINEX files.
> 
> The introduction of PWL offsets can, in a first step, already be achieved through estimating and reporting ERP offsets at 0h (before start of session), 0h (within the session) and 0h (after end of session) for all sessions which have the "odd" IVS starting times. For sessions from 0h to 0h UT, as in the latter CONT campaigns, this is even easier because the full information is comprised in the two 0h epochs. The apriori values will be reported unambiguously, facilitate combination, and improve the IVS results. Further refinements in time resolution can then be tested, discussed and introduced as a joint effort of all ACs.

We should check if ASCOT does this, and if not - fix it.

**Comment by TobNilsson** [comment]
ASCOT can estimate ERP (and other parameters) as PWL offsets. In one of the latest updates the possibility of having the PWL offsets at integer hours was added. To use this, specify the option "int_hours=true" under cpwlf (if not, the fist epoch of the pwlf will be the epoch of the first observation, which is not necessarily an integer hour). 
A solution from ASCOT contributed to the PWLO Test project, coordinated by Axel Nothnagel. The first results of this project were presented during the 12th IVS General Meeting and a paper was submitted to the proceedings of the conference.
